//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DopBally
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int purchase_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public string service { get; set; }
        public float price { get; set; }
        public System.DateTime date_add { get; set; }
        public System.DateTime date_end { get; set; }
        public bool done { get; set; }
        public bool registry { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual employers employers { get; set; }
    }
}
